### ISSUE TITLE
Praktijkvoorbeelden toevoegen aan BOMOS de  verdieping 

### ISSUE THREAD

**Issue by isik001** [Logius-standaarden/BOMOS-Verdieping#12]
### Omschrijving

GEONOVUM rekenmodel toevoegen aan BOMOS de Verdiepng, verder is de vraag ook aan andere klankbordleden nog meer praktijk voorbelden toe te voegen.  Dus van TNO, Kennis net IHW en RIONED.

### Naam

Güldeniz Isik 

### Email

guldeniz.ozdemirisik@logius.nl

### Organisatie

Logius

**Comment by edwinwisse** [comment]
Ook CCvD als voorbeeld voor een gezamenlijk strategische overleg opnemen.

**Comment by edwinwisse** [comment]
En github in het proces van Logius...

**Comment by edwinwisse** [comment]
resolved by #14

**Comment by wisze** [comment]
Was nog ter review tot 1 september. Er zijn geen opmerkingen meer binnengekomen. Toch heropend om het weer op de agenda te krijgen.
