### ISSUE TITLE
Breng verwijzing naar sectie 3.2 Architectuur aan in sectie 4.1.7

### ISSUE THREAD

**Issue by WvandenBerg** [Logius-standaarden/BOMOS-Verdieping#13]
### Soort

- [ ] Tekstuele fout
- [ ] Verbetersuggestie
- [X] Onduidelijke tekst

### Omschrijving

**huidige tekst**: 

> In een ander deel wordt dieper ingegaan op de relatie met andere standaarden.

**suggestie**:
> In **sectie 3.2** wordt dieper ingegaan op de relatie met andere standaarden.

### Naam

Wouter van den Berg

### Organisatie

TNO

**Comment by isik001** [comment]
Verwijzing aangebracht en afgelosten. zie 4..1.7

**Comment by wisze** [comment]
Gesloten, besproken en goedgekeurd in klankbord 26-6-2023
