### ISSUE TITLE
Lifecyclemanagement van standaarden in BOMOS

### ISSUE THREAD

**Issue by edwinwisse** [Logius-standaarden/BOMOS-Verdieping#22]
### Omschrijving

BOMOS is, zoals de naam al aangeeft, gericht op het ontwikkelen en beheren van standaarden. De nadruk ligt in de documentatie op het opzetten van governance, kwaliteit en het inrichten van een beheerproces. 
Wij merken dat de wereld van standaarden in beweging is. In de GDI is _standaarden boven voorzieningen_ als principe opgenomen. Daarmee winnen standaarden aan belang binnen de GDI en daarmee ook goed beheer en actualiteit van standaarden. Ook wanneer een standaard voor de (Nederlandse) stakeholders voldoet kan het zinnig zijn om regelmatig het nut en noodzaak van een standaard tegen het licht te houden. Binnen EU kader wordt een aantal _acts_ uitgewerkt (zoals bijvoorbeeld het _onze only technical system_) waarbinnen standaarden ontwikkeld worden.  Deze standaarden kunnen de binnen Nederland toegepaste standaarden op termijn vervangen. Hetzelfde geldt voor internationale standaarden  in het algemeen. Om een in Nederland toegepaste standaarden actueel te houden stellen we voor lifecycle management voor (GDI) standaarden in te richten waarbij standaarden ook uitgefaseerd worden wanneer vervangende standaarden beschikbaar komen. 
Hieronder een concept tekst voor een voorstel voor de Architectuurraad GDI. Graag horen we van het BOMOS klankbord of het nuttig is lifecycle management ook in BOMOS kader uit te werken.

**Voorstel life-cycle management**
Het principe standaarden boven voorzieningen is één van de basisprincipes van de GDI. Standaarden moeten actueel gehouden worden, en aangepast worden op de eisen van de diensten van stakeholders. Onder meer moeten bij Logius in beheer zijnde GDI standaarden meegaan met de ontwikkelingen van onderliggende standaarden. Op dit moment gebruiken we in de GDI standaarden die in sommige gevallen niet up to date zijn. Bijvoorbeeld omdat ze op een onderliggende standaard zijn gebaseerd die niet meer in beheer is. Om dit te verbeteren wordt de architectuurraad gevraagd in te stemmen met het principe van lifecycle management. Dit betekent dat de status van standaarden actief moet worden bijgehouden en dat gestuurd wordt op het actueel blijven van standaarden. 

**Actief beheer en het n-1 principe**
Een standaard maakt in veel gevallen gebruik van een onderliggende standaard. Hierbij geldt het principe dat een standaard altijd gebaseerd moet zijn op een actief beheerde onderliggende standaard die niet meer dan 1 versie achterloopt op de mees recente versie. Actief beheer is noodzakelijk omdat alleen dan wijzigingsvoorstellen in behandeling kunnen worden genomen . 

**Relatie met BOMOS**
Het Beheer en Ontwikkelmodel Open Standaarden (BOMOS) is een handreiking voor governance van het beheer van open standaarden. BOMOS legt geen principes op bevat geen aanbevelingen voor life cycle management. Logius wil life cycle management wel als best practice opnemen en zal dit voorstellen aan de BOMOS stakeholders bij het volgende klankbord. 

**Digikoppeling ebMS2 als case**
De ebMS koppelvlakspecificatie maakt deel uit van de Diigkoppeling standaard. Deze is nu gebaseerd op ebMS2. De ebMS2 standaard wordt niet meer actief beheerd. De opvolger van ebMS2 is ebMS3/AS4. Deze standaard is in actief beheer en vormt de basis van de Europese eDelivery standaard.
De ebMS2 specificatie refereert onder meer naar een verouderde encryptie standaard (SHA-1). Deze wordt nergens meer toegepast omdat deze met moderne computers (en ook met niet meer zo moderne computers) gemakkelijk te kraken is. In de Digikoppeling ebMS koppelvlakspecificatie is dan ook aangegeven dat gebruik gemaakt wordt van een verbeterde versie (SHA-2). Daarmee wijkt Digikoppeling strikt genomen wel af van de onderliggende standaard.
In dit geval zou noodzaak van modernisering van Digikoppeling ebMS een gevolg zijn van life cycle management. Dit vereenvoudigt de argumentatie voor modernisering en leidt tot actuelere standaarden. 

### Naam

Edwin Wisse

### Email

edwin.wisse@logius.nl

### Organisatie

Logius

resolves #23

**Comment by wisze** [comment]
Uit te werken in BOMOS Verdieping. Beschrijf in BOMOS Verdieping wat life cycle management is en wat de gevolgen zijn voor standaardenbeheer. Met name afhenkelijkheden van standaarden van onderliggende standaarden is een aandachtspunt. Als een onderliggende standaard end-of-life wordt moet een standaard gebruik maken van een nieuwe versie van de onderliggende standaard.
